### ISSUE TITLE
Use of batch_ans in forward method of SimpleLSTM

### ISSUE THREAD

**Issue by Gopal-Dahale** [andrewschreiber/hs-math-nlp#12]
The [code](https://github.com/andrewschreiber/hs-math-nlp/blob/master/LSTM/simple.py#L72) uses `batch_ans` as one of the parameters in the forward prop of simpleLSTM. This may be fine during training but how are we supposed to make predictions as answers won't be present at the time of predictions?

**Comment by ProxJ** [comment]
Hi, it seems as if all LSTM models use this. Check this: https://towardsdatascience.com/a-detailed-guide-to-pytorchs-nn-transformer-module-c80afbc9ffb1 or this: https://github.com/bentrevett/pytorch-seq2seq for how to do inference. They basically loop until the decoder outputs `<eos>` or `max_len` is reached:

```python
    trg_indexes = [<sos_token_id>]

    for i in range(max_len):

        trg_tensor = torch.LongTensor(trg_indexes).unsqueeze(0).to(device)

        trg_mask = model.make_trg_mask(trg_tensor)
        
        with torch.no_grad():
            output, attention = model.decoder(trg_tensor, enc_src, trg_mask, src_mask)
        
        pred_token = output.argmax(2)[:,-1].item()
        
        trg_indexes.append(pred_token)

        if pred_token == trg_field.vocab.stoi[trg_field.eos_token]:
            break
```

**Comment by ProxJ** [comment]
Hi @Gopal-Dahale, it seems as if all attention models use this (from the implementations I've seen). Check this: https://towardsdatascience.com/a-detailed-guide-to-pytorchs-nn-transformer-module-c80afbc9ffb1 or this: https://github.com/bentrevett/pytorch-seq2seq for how to do inference. They basically loop until the decoder outputs `<eos>` or `max_len` is reached:

```python
    trg_indexes = [<sos_token_id>]

    for i in range(max_len):

        trg_tensor = torch.LongTensor(trg_indexes).unsqueeze(0).to(device)

        trg_mask = model.make_trg_mask(trg_tensor)
        
        with torch.no_grad():
            output, attention = model.decoder(trg_tensor, enc_src, trg_mask, src_mask)
        
        pred_token = output.argmax(2)[:,-1].item()
        
        trg_indexes.append(pred_token)

        if pred_token == <eos_token_id>:
            break
```
